"""add Max Calls and functions to User

Revision ID: 8eea3807174a
Revises: dc75b94f55f3
Create Date: 2018-07-30 20:03:21.278129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eea3807174a'
down_revision = 'dc75b94f55f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('calls_this_month', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('last_call', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('max_calls_per_month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'max_calls_per_month')
    op.drop_column('user', 'last_call')
    op.drop_column('user', 'calls_this_month')
    # ### end Alembic commands ###
