"""add Payment table

Revision ID: 27aea0528da3
Revises: abdc5b1b69ae
Create Date: 2018-07-30 18:22:11.102183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27aea0528da3'
down_revision = 'abdc5b1b69ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unix', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('username', sa.Integer(), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('payment_gross', sa.Float(), nullable=True),
    sa.Column('payment_fee', sa.Float(), nullable=True),
    sa.Column('payment_net', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(length=15), nullable=True),
    sa.Column('txn_id', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_payment_date'), 'payment', ['payment_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_payment_date'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
