"""add user translations

Revision ID: d9430885af8a
Revises: 8eea3807174a
Create Date: 2018-07-31 15:36:02.871900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9430885af8a'
down_revision = '8eea3807174a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_word_list', sa.Column('user_translations', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_word_list', 'user_translations')
    # ### end Alembic commands ###
