"""add Payment table correct

Revision ID: dc75b94f55f3
Revises: 27aea0528da3
Create Date: 2018-07-30 18:23:24.624031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc75b94f55f3'
down_revision = '27aea0528da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_payment_date', table_name='payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_payment_payment_date', 'payment', ['payment_date'], unique=False)
    # ### end Alembic commands ###
